### ISSUE TITLE
Feature request: D'ni time display in KI

### ISSUE THREAD

**Issue by MareinK** [H-uru/Plasma#1189] opened 2022-06-04 20:03 UTC
In addition to the existing KI time, it might be cool to display the D'ni date and time in the big KI.

For example, it could be formatted as `9678 leebro 7 - 1.24.7` or similar, and shown in the area to the left of the existing time (shown using a purple rectangle in the below image).

Side-thought: maybe it would be interesting if this KI feature is gained from a special KI terminal, adding a new collectible (similar to one in the Eder Tomahn). The same could be done for #1185. Perhaps there will be some suitable fan Age (e.g. one related to D'ni timekeeping and/or writing). 

![image](https://user-images.githubusercontent.com/1388357/172023622-73385eae-3b7a-4109-bd2c-709a7799e2d3.png)

**Comment by Hoikas** [comment] 2022-06-04 20:05
Dupe of #1187

**Closed by Hoikas** 2022-06-04 20:05 UTC
