### ISSUE TITLE
Scroll wheel support for GUI lists

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#1188] opened 2022-06-04 19:57 UTC
It is a **huge** pain needing to click the up/down arrows to page through things like the Age Players sidebar list, the chat history, and the neighbours/recents lists in the KI.

Can we make these mouse scrollable with the wheel?

For chat specifically, could we add pageUp and pageDown and End hotkey support?

**Comment by Hoikas** [comment] 2022-06-04 20:09
Duplicate of #1088.

**Closed by Hoikas** 2022-06-04 20:09 UTC
Labels: Client, Wishlist, Enhancement
